version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '09:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 10
    groups:
      fontawesome:
        patterns:
          - '@fortawesome*'
      astro:
        patterns:
          - 'astro'
          - '@astrojs*'
      testing:
        patterns:
          - '@testing-library*'
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '09:00'
      timezone: 'Europe/Madrid'
